### ISSUE TITLE
Invalid jwt token

### ISSUE THREAD

**Issue by AlgoApi** [club100-blum/Blum#1]
Ошибка при запросе баланса и попытке начать игру
![image](https://github.com/user-attachments/assets/4c83e27c-4415-4203-aeca-e29acad96dc4)
на скрине фрагмент кода вызывающий ошибку, возможно у blum появилась защита
Couldn't play game; msg: {"message":"Invalid jwt token"} play_passes: 
mode: lazy

**Comment by club100-blum** [comment]
fixed
